// build.gradle (at root)
plugins {
    id 'org.springframework.boot' version '3.2.0' apply false
    id 'io.spring.dependency-management' version '1.1.4' apply false
}

// Configure all projects
allprojects {
    repositories {
        mavenCentral()
    }
}

// Configure all subprojects
subprojects {
    apply plugin: 'java' // Apply java to both 'app' and 'common'
}